### ISSUE TITLE
android suggestions

### ISSUE THREAD

**Issue by fjgal** [weplenish/flutter_wifi_connect#3]
Hi,

First, thanks for creating this plugins with minimal dependencies and using the latest Android APIs.

I'd like to propose some improvements for the Android pluging.

* on Android API < 29 support connection without requiring location permissions.

`wifiManager.connectionInfo.ssid` requires location permission, as an alternative the ssid could be obtained from `info.getExtraInfo()`. 

In the change receiver once could check both connectionInfo and extraInfo to cover both cases

```
          result.success(wifiManager.connectionInfo.ssid == wifiConfiguration.SSID || info.getExtraInfo() == wifiConfiguration.SSID)
```

* implement `disconnect` method on Android

Some application need to programatically disconnect from the peer to peer network and go back to the "default" WiFi/Internet connection.  On API < 29 this could be done by calling `wifiManager.disconnect()`, not the nicest but it works. On API >=29, it is a bit more involved but cleaner: unregister the network callback, and unbind the process from the network.

Note: on API >= 29, the network callback was being removed on `onAvailable` which caused the connection to be disconnected as soon as it was connected.

* issue with wpa2/wpa3 on Android 11

On Android 11 (didn't test on Android 10) `setWpa2Passphrase` and `setWpa3Passphrase` are mutually exclusive. I propose to add an argument to explicitly ask for WPA3 when required by the application. The error is:

```
E/flutter (31808): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, only one of setIsEnhancedOpen, setWpa2Passphrase,setWpa3Passphrase, setWpa2EnterpriseConfig or setWpa3EnterpriseConfig can be invoked for network specifier, null, java.lang.IllegalStateException: only one of setIsEnhancedOpen, setWpa2Passphrase,setWpa3Passphrase, setWpa2EnterpriseConfig or setWpa3EnterpriseConfig can be invoked for network specifier
```

I'm submitting a PR with the above proposed changes. Happy to discuss them. Tested on Android 8.1 (Nexus 5X) and Android 11 (Pixel 2(

Thank you!

**Comment by vipero07** [comment]
no need to discuss, I agree with your assessments. This was a quick prototype, so its nice to be able to move it forward. I plan on addressing some other issues I've come across, just been busy over the holiday season. Thanks a ton.

My only comment is regarding the location permissions on <29, I believe even with that change location permissions are still necessary due to the nature of connecting to alternative WIFI devices. However it would remove the requirement in the case of getSSID here https://github.com/HerbiaEra/flutter_wifi_connect/blob/6632122edb12b7293af596e7cd3e9c6fec5439f5/android/src/main/kotlin/com/weplenish/flutter_wifi_connect/FlutterWifiConnectPlugin.kt#L71 has i implemented it.

I'm sure you've noticed the primary reasons I didn't implement certain things in android is because there is no ability to implement them in iOS, so I've left a few things in limbo as a result.

**Comment by fjgal** [comment]
Thanks @vipero07 for accepting my contribution and merging it so quickly!

Regarding permissions this is what I have so far and it is working fine on Android 8.1 and 11.0. 

```xml
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />
```

My understanding is that as long as we don't perform a wifi scan, or ask for the currently connected SSID (unless the connection was triggered by us. I think for the use case of IoT device pairing (which I believe it is also your use case) we will not need location permissions.

Please tag me once you publish a new version in pub.dev, in the meantime I'm referencing the commit hash.

**Comment by vipero07** [comment]
pub.dev has been updated to include your modifications.

On android pre 29 for it to connect to an ssid by prefix it does a wifi scan. So only in the case of having the exact ssid would it not require location permission. Unfortunately for me the device I'm dealing with is prefixed. However you are correct the other cases wouldn't require location permissions. Honestly it didn't occur to me. Thanks again for the insight.
