### ISSUE TITLE
Library not ready to use?

### ISSUE THREAD

**Issue by surister** [weplenish/flutter_wifi_connect#6]
Many functions throw `MissingPluginException`, like `FlutterWifiConnect.deactivateWifi()` and such.

**Comment by vipero07** [comment]
On what platform?

**Comment by vipero07** [comment]
Both activate and deactivate are currently unimplemented. They don't exist in iOS so adding them for a cross platform plugin felt awkward since it would result in unique implementations by the library implementer. However if you require them I can put some time into adding them. They already exist in the flutter connectivity package. This package was intended to get the new connect to wifi by ssid and ssid prefix in iOS and Android under the same hood for flutter, and both of those parts work.

Alternatively we can remove them from the flutter package to better align with expected use.

**Comment by surister** [comment]
Yeah, it seemed weird `main/lib/flutter_wifi_connect.dart` had all these methods that are actually not implemented, should perhaps remove them or note it on the readme. Cheers.

**Comment by techno-disaster** [comment]
@vipero07 if possible could you add these in a different branch so devs who need it can use from there?
